### ISSUE TITLE
[Feature Request] Show empty glass frame in-world, but hide when item put inside

### ISSUE THREAD

**Issue by Disketaa** [ItsFelix5/GlassItemFrames#1]
![image](https://github.com/user-attachments/assets/7934d7ef-8a19-4dfd-8dc7-cad8cb6984cb)
![image](https://github.com/user-attachments/assets/a833bce9-49f3-4631-ae8f-0ec4428f3cde)

(Maybe glass particles will appear after glass panel hides)

**Comment by ItsFelix5** [comment]
After 2 months, it is finally here! Sorry for the long wait
